version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: 1q2w3e4r
      MYSQL_ONETIME_PASSWORD: yes
      TZ: Asia/Bangkok
    restart: always
    ports:
      - "3306:3306"
    networks:
      - mysqlnetwork

networks:
  mysqlnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.21.0.0/16
          ip_range: 10.21.5.0/24
          gateway: 10.21.5.254

